.\"
.\" libexplain - Explain errno values returned by libc functions
.\" Copyright (C) 2008, 2009 Peter Miller
.\" Written by Peter Miller <pmiller@opensource.org.au>
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
.\" General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program. If not, see <http://www.gnu.org/licenses/>.
.\"
.TH libexplain 3
.SH NAME
libexplain \- Explain errno values returned by libc functions
.XX "libexplain(3)" "Explain errno values returned by libc functions"
.SH SYNOPSIS
cc ... -lexplain;
.sp
#include <libexplain/libexplain.h>
.SH DESCRIPTION
The libexplain library exists to give explanations of error reported by
system calls.  The error message returned by \f[I]strerror\fP(3) tend to
be quite cryptic.  By providing a specific error report for each system
call, a more detailed error message is possible, usually identifying and
describing the specific cause from amongst the numerous meanings each
\f[I]errno\fP value maps to.
.SS Race Condition
The explanation of the cause of an error is dependent on the environment
of the error to remain unchanged, so that when libexplain gets around to
looking for the cause, the cause is still there.  On a running system,
and particularly a multi-user system, this is not always possible.
.PP
If an incorrect explanation is provided,
it is possible because the cause is no longer present.
.SS Environment Variable
The \f[CW]LIBEXPLAIN_OPTIONS\fP environment variable may be used
to control some of the content in the messages.
.TP 8n
debug
Additional debugging messages for libexplain developers.
Not generally useful to clients of the library.
.TP 8n
no-numeric-errno
This option suppresses the numeric \f[I]errno\fP value from being
included in the message, \f[I]e.g.\fP \[lq](ENOENT)\[rq] rather than
\[lq](2, ENOENT)\[rq].
This option is more generally of use in automated testing, to prevent
UNIX dialect differences from producing false negatives.
.TP 8n
no-dialect-specific
The option suppresses explanatory text specific to a particular UNIX dialect.
It also suppresses printing system specific maximums.
This option is more generally of use in automated testing, to prevent
UNIX dialect differences from producing false negatives.
.TP 8n
no-program-name
By default the libexplain_*_or_die functions include the name of the
executing program at the start of the error message, and this helps
users understand which command is throwing the error.
This option may be used to suppress the inclusion of the program name,
which may be of some interest to script writers.
Program developers can use the \f[I]libexplain_program_name_set\fP(3)
function is set the name of the command, if they wish to override
the name that libexplain would otherwise obtain from the operating system.
Program developers can use the \f[I]libexplain_program_name_assemble\fP(3)
function is they wish to trump the environment variable.
.SH Supported System Calls
Each supported system call has its own \f[I]man\fP page.
.\" please keep the following list sorted
.\" ----------  A  ---------------------------------------------------------
.TP 8n
\f[I]libexplain_accept\fP(3)
Explain \f[I]accept\fP(2) errors
.TP 8n
\f[I]libexplain_accept_or_die\fP(3)
accept a connection on a socket and report errors
.TP 8n
\f[I]libexplain_access\fP(3)
Explain \f[I]access\fP(2) errors
.TP 8n
\f[I]libexplain_access_or_die\fP(3)
check permissions for a file and report errors
.\" ----------  B  ---------------------------------------------------------
.TP 8n
\f[I]libexplain_bind\fP(3)
Explain \f[I]bind\fP(2) errors
.TP 8n
\f[I]libexplain_bind_or_die\fP(3)
bind a name to a socket and report errors
.\" ----------  C  ---------------------------------------------------------
.TP 8n
\f[I]libexplain_chdir\fP(3)
Explain \f[I]chdir\fP(2) errors
.TP 8n
\f[I]libexplain_chdir_or_die\fP(3)
change working directory and report errors
.TP 8n
\f[I]libexplain_chmod\fP(3)
Explain \f[I]chmod\fP(2) errors
.TP 8n
\f[I]libexplain_chmod_or_die\fP(3)
change permissions of a file and report errors
.TP 8n
\f[I]libexplain_chown\fP(3)
Explain \f[I]chown\fP errors
.TP 8n
\f[I]libexplain_chown_or_die\fP(3)
change ownership of a file and report errors
.TP 8n
\f[I]libexplain_close\fP(3)
Explain \f[I]close\fP(2) errors
.TP 8n
\f[I]libexplain_close_or_die\fP(3)
close a file descriptor and report errors
.TP 8n
\f[I]libexplain_closedir\fP(3)
Explain \f[I]closedir\fP(3) errors
.TP 8n
\f[I]libexplain_closedir_or_die\fP(3)
close a directory and report errors
.TP 8n
\f[I]libexplain_connect\fP(3)
Explain \f[I]connect\fP(2) errors
.TP 8n
\f[I]libexplain_connect_or_die\fP(3)
initiate a connection on a socket and report errors
.TP 8n
\f[I]libexplain_creat\fP(3)
Explain \f[I]creat\fP(2) errors
.TP 8n
\f[I]libexplain_creat_or_die\fP(3)
create and open a file and report errors
.\" ----------  D  ---------------------------------------------------------
.TP 8n
\f[I]libexplain_dup\fP(3)
Explain \f[I]dup\fP(2) errors
.TP 8n
\f[I]libexplain_dup_or_die\fP(3)
duplicate a file descriptor and report errors
.TP 8n
\f[I]libexplain_dup2\fP(3)
Explain \f[I]dup2\fP(2) errors
.TP 8n
\f[I]libexplain_dup2_or_die\fP(3)
duplicate a file descriptor and report errors
.\" ----------  E  ---------------------------------------------------------
.TP 8n
\f[I]libexplain_execve\fP(3)
Explain \f[I]execve\fP(2) errors
.TP 8n
\f[I]libexplain_execve_or_die\fP(3)
execute program and report errors
.TP 8n
\f[I]libexplain_execvp\fP(3)
Explain \f[I]execvp\fP(3) errors
.TP 8n
\f[I]libexplain_execvp_or_die\fP(3)
execute program and report errors
.\" ----------  F  ---------------------------------------------------------
.TP 8n
\f[I]libexplain_fchdir\fP(3)
Explain \f[I]fchdir\fP(2) errors
.TP 8n
\f[I]libexplain_fchmod\fP(3)
Explain \f[I]fchmod\fP(2) errors
.TP 8n
\f[I]libexplain_fchmod_or_die\fP(3)
change permissions of a file and report errors
.TP 8n
\f[I]libexplain_fchown\fP(3)
Explain \f[I]fchown\fP(2) errors
.TP 8n
\f[I]libexplain_fchown_or_die\fP(3)
change ownership of a file and report errors
.TP 8n
\f[I]libexplain_fclose\fP(3)
Explain \f[I]fclose\fP(2) errors
.TP 8n
\f[I]libexplain_fclose_or_die\fP(3)
close a stream and report errors
.TP 8n
\f[I]libexplain_fcntl\fP(3)
Explain \f[I]fcntl\fP(2) errors
.TP 8n
\f[I]libexplain_fcntl_or_die\fP(3)
Manipulate a file descriptor and report errors
.TP 8n
\f[I]libexplain_fdopen\fP(3)
Explain \f[I]fdopen\fP(3) errors
.TP 8n
\f[I]libexplain_fdopen_or_die\fP(3)
stream open function and report errors
.TP 8n
\f[I]libexplain_ferror\fP(3)
Explain \f[I]ferror\fP(3) errors
.TP 8n
\f[I]libexplain_ferror_or_die\fP(3)
check stream status and report errors
.TP 8n
\f[I]libexplain_fflush\fP(3)
Explain \f[I]fflush\fP(2) errors
.TP 8n
\f[I]libexplain_fflush_or_die\fP(3)
flush a stream and report errors
.TP 8n
\f[I]libexplain_fgetc\fP(3)
Explain \f[I]fgetc\fP(3) errors
.TP 8n
\f[I]libexplain_fgetc_or_die\fP(3)
input of characters and report errors
.TP 8n
\f[I]libexplain_fgets\fP(3)
Explain \f[I]fgets\fP(3) errors
.TP 8n
\f[I]libexplain_fgets_or_die\fP(3)
input of strings and report errors
.TP 8n
\f[I]libexplain_fopen\fP(3)
Explain \f[I]fopen\fP(3) errors
.TP 8n
\f[I]libexplain_fopen_or_die\fP(2)
open files and report errors
.TP 8n
\f[I]libexplain_fork\fP(3)
Explain \f[I]fork\fP(2) errors
.TP 8n
\f[I]libexplain_fork_or_die\fP(3)
create a child process and report errors
.TP 8n
\f[I]libexplain_fpathconf\fP(3)
Explain \f[I]fpathconf\fP(3) errors
.TP 8n
\f[I]libexplain_fpathconf_or_die\fP(3)
get configuration values for files and report errors
.TP 8n
\f[I]libexplain_fputc\fP(3)
Explain \f[I]fputc\fP(3) errors
.TP 8n
\f[I]libexplain_fputc_or_die\fP(3)
output of characters and report errors
.TP 8n
\f[I]libexplain_fread\fP(3)
Explain \f[I]fread\fP(3) errors
.TP 8n
\f[I]libexplain_fread_or_die\fP(3)
binary stream input and report errors
.TP 8n
\f[I]libexplain_freopen\fP(3)
Explain \f[I]freopen\fP(3) errors
.TP 8n
\f[I]libexplain_freopen_or_die\fP(3)
open files and report errors
.TP 8n
\f[I]libexplain_fstat\fP(3)
Explain \f[I]fstat\fP(3) errors
.TP 8n
\f[I]libexplain_fstat_or_die\fP(3)
get file status and report errors
.TP 8n
\f[I]libexplain_ftruncate\fP(3)
Explain \f[I]ftruncate\fP(2) errors
.TP 8n
\f[I]libexplain_ftruncate_or_die\fP(3)
truncate a file to a specified length and report errors
.TP 8n
\f[I]libexplain_futimes\fP(3)
Explain \f[I]futimes\fP(3) errors
.TP 8n
\f[I]libexplain_futimes_or_die\fP(3)
Execute \f[I]futimes\fP(3) and report errors
.TP 8n
\f[I]libexplain_fwrite\fP(3)
Explain \f[I]fwrite\fP(3) errors
.TP 8n
\f[I]libexplain_fwrite_or_die\fP(3)
binary stream output and report errors
.\" ----------  G  ---------------------------------------------------------
.TP 8n
\f[I]libexplain_getaddrinfo\fP(3)
Explain \f[I]getaddrinfo\fP(3) errors
.TP 8n
\f[I]libexplain_getaddrinfo_or_die\fP(3)
network address and and report errors
.TP 8n
\f[I]libexplain_getc\fP(3)
Explain \f[I]getc\fP(3) errors
.TP 8n
\f[I]libexplain_getc_or_die\fP(3)
input of characters and report errors
.TP 8n
\f[I]libexplain_getchar\fP(3)
Explain \f[I]getchar\fP(3) errors
.TP 8n
\f[I]libexplain_getchar_or_die\fP(3)
input of characters and report errors
.TP 8n
\f[I]libexplain_getcwd\fP(3)
Explain \f[I]getcwd\fP(2) errors
.TP 8n
\f[I]libexplain_getcwd_or_die\fP(3)
Get current working directory and report errors
.TP 8n
\f[I]libexplain_getpeername\fP(3)
Explain \f[I]getpeername\fP(2) errors
.TP 8n
\f[I]libexplain_getpeername_or_die\fP(3)
Execute\f[I]getpeername\fP(2) and report errors
.TP 8n
\f[I]libexplain_getrlimit\fP(3)
Explain \f[I]getrlimit\fP(2) errors
.TP 8n
\f[I]libexplain_getrlimit_or_die\fP(3)
get resource limits and report errors
.TP 8n
\f[I]libexplain_getsockname\fP(3)
Explain \f[I]getsockname\fP(2) errors
.TP 8n
\f[I]libexplain_getsockname_or_die\fP(3)
Execute \f[I]getsockname\fP(2) and report errors
.TP 8n
\f[I]libexplain_getsockopt\fP(3)
Explain \f[I]getsockopt\fP(2) errors
.TP 8n
\f[I]libexplain_getsockopt_or_die\fP(3)
Execute \f[I]getsockopt\fP(2) and report errors
.TP 8n
\f[I]libexplain_gettimeofday\fP(3)
Explain \f[I]gettimeofday\fP(2) errors
.TP 8n
\f[I]libexplain_gettimeofday_or_die\fP(3)
get time and report errors
.\" ----------  H  ---------------------------------------------------------
.\" ----------  I  ---------------------------------------------------------
.TP 8n
\f[I]libexplain_ioctl\fP(3)
Explain \f[I]ioctl\fP(2) errors
.TP 8n
\f[I]libexplain_ioctl_or_die\fP(3)
Execute \f[I]ioctl\fP(2) and report errors
.\" ----------  K  ---------------------------------------------------------
.\" ----------  L  ---------------------------------------------------------
.TP 8n
\f[I]libexplain_lchown\fP(3)
Explain \f[I]lchown\fP(2) errors
.TP 8n
\f[I]libexplain_lchown_or_die\fP(3)
change ownership of a file and report errors
.TP 8n
\f[I]libexplain_link\fP(3)
Explain \f[I]link\fP(2) errors
.TP 8n
\f[I]libexplain_link_or_die\fP(3)
make a new name for a file and report errors
.TP 8n
\f[I]libexplain_listen\fP(3)
Explain \f[I]listen\fP(2) errors
.TP 8n
\f[I]libexplain_listen_or_die\fP(3)
listen for connections on a socket and report errors
.TP 8n
\f[I]libexplain_lseek\fP(3)
Explain \f[I]lseek\fP(2) errors
.TP 8n
\f[I]libexplain_lseek_or_die\fP(3)
reposition file offset and report errors
.TP 8n
\f[I]libexplain_lstat\fP(3)
Explain \f[I]lstat\fP(2) errors
.TP 8n
\f[I]libexplain_lstat_or_die\fP(3)
get file status and report errors
.\" ----------  M  ---------------------------------------------------------
.TP 8n
\f[I]libexplain_malloc\fP(3)
Explain \f[I]malloc\fP(3) errors
.TP 8n
\f[I]libexplain_malloc_or_die\fP(3)
Execute \f[I]malloc\fP(3) and report errors
.TP 8n
\f[I]libexplain_mkdir\fP(3)
Explain \f[I]mkdir\fP(2) errors
.TP 8n
\f[I]libexplain_mkdir_or_die\fP(3)
create directory and report errors
.\" ----------  N  ---------------------------------------------------------
.\" ----------  O  ---------------------------------------------------------
.TP 8n
\f[I]libexplain_open\fP(3)
Explain \f[I]open\fP(2) errors
.TP 8n
\f[I]libexplain_open_or_die\fP(3)
open files and report errors
.TP 8n
\f[I]libexplain_opendir\fP(3)
Explain \f[I]opendir\fP(3) errors
.TP 8n
\f[I]libexplain_opendir_or_die\fP(3)
open a directory and report errors
.\" ----------  P  ---------------------------------------------------------
.TP 8n
\f[I]libexplain_pathconf\fP(3)
Explain \f[I]pathconf\fP(3) errors
.TP 8n
\f[I]libexplain_pathconf_or_die\fP(3)
get configuration values for files and report errors
.TP 8n
\f[I]libexplain_pclose\fP(3)
Explain \f[I]pclose\fP(3) errors
.TP 8n
\f[I]libexplain_pclose_or_die\fP(3)
Execute \f[I]pclose\fP(3) and report errors
.TP 8n
\f[I]libexplain_pipe\fP(3)
Explain \f[I]pipe\fP(2) errors
.TP 8n
\f[I]libexplain_pipe_or_die\fP(3)
Execute \f[I]pipe\fP(2) and report errors
.TP 8n
\f[I]libexplain_popen\fP(3)
Explain \f[I]popen\fP(3) errors
.TP 8n
\f[I]libexplain_popen_or_die\fP(3)
Execute \f[I]popen\fP(3) and report errors
.TP 8n
\f[I]libexplain_putc\fP(3)
Explain \f[I]putc\fP(3) errors
.TP 8n
\f[I]libexplain_putc_or_die\fP(3)
output of characters and report errors
.TP 8n
\f[I]libexplain_putchar\fP(3)
Explain \f[I]putchar\fP(3) errors
.TP 8n
\f[I]libexplain_putchar_or_die\fP(3)
output of characters and report errors
.\" ----------  Q  ---------------------------------------------------------
.\" ----------  R  ---------------------------------------------------------
.TP 8n
\f[I]libexplain_read\fP(3)
Explain \f[I]read\fP(2) errors
.TP 8n
\f[I]libexplain_read_or_die\fP(3)
read from a file descriptor and report errors
.TP 8n
\f[I]libexplain_readdir\fP(3)
Explain \f[I]readdir\fP(3) errors
.TP 8n
\f[I]libexplain_readdir_or_die\fP(3)
read a directory and report errors
.TP 8n
\f[I]libexplain_readlink\fP(3)
Explain \f[I]readlink\fP(2) errors
.TP 8n
\f[I]libexplain_readlink_or_die\fP(3)
read value of a symbolic link and report errors
.TP 8n
\f[I]libexplain_realloc\fP(3)
Explain \f[I]realloc\fP(3) errors
.TP 8n
\f[I]libexplain_realloc_or_die\fP(3)
Execute \f[I]realloc\fP(3) and report errors
.TP 8n
\f[I]libexplain_rename\fP(3)
Explain \f[I]rename\fP(2) errors
.TP 8n
\f[I]libexplain_rename_or_die\fP(3)
change the name or location of a file and report errors
.TP 8n
\f[I]libexplain_rmdir\fP(3)
Explain \f[I]rmdir\fP(2) errors
.TP 8n
\f[I]libexplain_rmdir_or_die\fP(3)
delete a directory and report errors
.\" ----------  S  ---------------------------------------------------------
.TP 8n
\f[I]libexplain_select\fP(3)
Explain \f[I]select\fP(2) errors
.TP 8n
\f[I]libexplain_select_or_die\fP(3)
execute \f[I]select\fP(2) and report errors
.TP 8n
\f[I]libexplain_setsockopt\fP(3)
Explain \f[I]setsockopt\fP(2) errors
.TP 8n
\f[I]libexplain_setsockopt_or_die\fP(3)
execute \f[I]setsockopt\fP(2) and report errors
.TP 8n
\f[I]libexplain_socket\fP(3)
Explain \f[I]socket\fP(2) errors
.TP 8n
\f[I]libexplain_socket_or_die\fP(3)
create an endpoint for communication and report errors
.TP 8n
\f[I]libexplain_stat\fP(3)
Explain \f[I]stat\fP(2) errors
.TP 8n
\f[I]libexplain_symlink\fP(3)
Explain \f[I]symlink\fP(2) errors
.TP 8n
\f[I]libexplain_symlink_or_die\fP(3)
make a new name for a file and report errors
.TP 8n
\f[I]libexplain_system\fP(3)
Explain \f[I]system\fP(3) errors
.TP 8n
\f[I]libexplain_system_or_die\fP(3)
execute a shell command and report errors
.\" ----------  T  ---------------------------------------------------------
.TP 8n
\f[I]libexplain_truncate\fP(3)
Explain \f[I]truncate\fP(2) errors
.TP 8n
\f[I]libexplain_truncate_or_die\fP(3)
truncate a file to a specified length and report errors
.\" ----------  U  ---------------------------------------------------------
.TP 8n
\f[I]libexplain_unlink\fP(3)
Explain \f[I]unlink\fP(2) errors
.TP 8n
\f[I]libexplain_unlink_or_die\fP(3)
delete a file and report errors
.TP 8n
\f[I]libexplain_utime\fP(3)
Explain \f[I]utime\fP(2) errors
.TP 8n
\f[I]libexplain_utime_or_die\fP(3)
change file last access and modification times and report errors
.\" ----------  V  ---------------------------------------------------------
.\" ----------  W  ---------------------------------------------------------
.TP 8n
\f[I]libexplain_wait\fP(3)
Explain \f[I]wait\fP(2) errors
.TP 8n
\f[I]libexplain_wait_or_die\fP(3)
wait for process to change state and report errors
.TP 8n
\f[I]libexplain_wait3\fP(3)
Explain \f[I]wait3\fP(2) errors
.TP 8n
\f[I]libexplain_wait3_or_die\fP(3)
wait for process to change state and report errors
.TP 8n
\f[I]libexplain_wait4\fP(3)
Explain \f[I]wait4\fP(2) errors
.TP 8n
\f[I]libexplain_wait4_or_die\fP(3)
wait for process to change state and report errors
.TP 8n
\f[I]libexplain_waitpid\fP(3)
Explain \f[I]waitpid\fP(2) errors
.TP 8n
\f[I]libexplain_waitpid_or_die\fP(3)
wait for process to change state and report errors
.TP 8n
\f[I]libexplain_write\fP(3)
Explain \f[I]write\fP(2) errors
.TP 8n
\f[I]libexplain_write_or_die\fP(3)
write to a file descriptor and report errors
.\" ----------  X  ---------------------------------------------------------
.\" ----------  Y  ---------------------------------------------------------
.\" ----------  Z  ---------------------------------------------------------
.\" ------------------------------------------------------------------------
.PP
There are plans for additional coverage.
This list is expected to expand in later releases of this library.
.SH SEE ALSO
.TP 8n
\f[I]errno\fP(3)
number of last error
.TP 8n
\f[I]strerror\fP(3)
return string describing error number
.SH COPYRIGHT
.if n .ds C) (C)
.if t .ds C) \(co
libexplain version \*(v)
.br
Copyright \*(C) 2008 Peter Miller
.SH AUTHOR
Written by Peter Miller <pmiller@opensource.org.au>
