.\"
.\" libexplain - Explain errno values returned by libc functions
.\" Copyright (C) 2008 Peter Miller
.\" Written by Peter Miller <millerp@canb.auug.org.au>
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
.\" General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program. If not, see <http://www.gnu.org/licenses/>.
.\"
.ds n) explain
.TH explain 1
.SH NAME
explain \- explain system call error messages
.XX "explain(1)" "explain system call error messages"
.SH SYNOPSIS
\f[B]\*(n)\fP
[
\f[I]option\fP
\&...
]
\f[I]function\fP
[
\f[I]argument\fP
\&...
]
.sp
.B \*(n)
.B \-\-version
.SH DESCRIPTION
The \*(n) command is used to decode an error return read from an
\f[I]strace\fP(1) listing, or silimar.  Because thisd is being
deciphered in a different process than the orginal, the results
will be less accurate than if the program itself were to use
\f[I]libexplain\fP(3).
.SS Functions
The functions understood include:
.\" ----------  A  ---------------------------------------------------------
.TP 8n
access \f[I]pathname\fP
The \f[I]access\fP(2) system call.
.\" ----------  B  ---------------------------------------------------------
.\" ----------  C  ---------------------------------------------------------
.TP 8n
chdir \f[I]pathname\fP
The \f[I]chdir\fP(2) system call.
.TP 8n
chmod \f[I]pathname\fP \f[I]permission-mode\fP
The \f[I]chmod\fP(2) system call.
.TP 8n
chown \f[I]pathname\fP \f[I]owner\fP \f[I]group\fP
The \f[I]chown\fP(2) system call.
.TP 8n
close \f[I]fildes\fP
The \f[I]close\fP(2) system call.
.TP 8n
closedir \f[I]dir\fP
The \f[I]closedir\fP(3) system call.
.TP 8n
creat \f[I]pathname\fP [ \f[I]permission-mode\fP
The \f[I]creat\fP(2) system call.
.\" ----------  D  ---------------------------------------------------------
.TP 8n
dup \f[I]fildes\fP
The \f[I]dup\fP(2) system call.
.\" ----------  E  ---------------------------------------------------------
.TP 8n
execve \f[I]pathname\fP \f[I]arg\fP...
The \f[I]execve\fP(2) system call.
.\" ----------  F  ---------------------------------------------------------
.TP 8n
fchdir \f[I]pathname\fP
The \f[I]fchdir\fP(2) system call.
.TP 8n
fcntl \f[I]fildes\fP \f[I]command\fP [ \f[I]arg\fP ]
The \f[I]fcntl\fP(2) system call.
.TP 8n
ferror \f[I]fp\fP
The \f[I]ferror\fP(3) system call.
.TP 8n
fgetc \f[I]fp\fP
The \f[I]fgetc\fP(3) system call.
.TP 8n
fgets \f[I]data\fP \f[I]data_size\fP \f[I]fp\fP
The \f[I]fgets\fP(3) system call.
.TP 8n
fork
The \f[I]fork\fP(2) system call.
.TP 8n
fread \f[I]ptr\fP \f[I]size\fP \f[I]nmemb\fP \f[I]fp\fP
The \f[I]fread\fP(3) system call.
.TP 8n
fopen \f[I]pathname\fP \f[I]mode\fP
The \f[I]fopen\fP(2) system call.
The \f[I]pathname\fP argument may need to be quoted to insulate white space and
punctuation from the shell.
The \f[I]mode\fP argument (a textual equivalent of the \f[I]open\fP
system call's \f[I]flags\fP argument).
See \f[I]fopen\fP(3) for more information.
.TP 8n
fstat \f[I]pathname\fP
The \f[I]fstat\fP(2) system call.
.TP 8n
ftruncate \f[I]fildes\fP \f[I]length\fP
The \f[I]ftruncate\fP(2) system call.
.\" ----------  G  ---------------------------------------------------------
.TP 8n
getc \f[I]fp\fP
The \f[I]getc\fP(3) system call.
.TP 8n
getchar
The \f[I]getchar\fP(3) system call.
.TP 8n
gettimeofday [ \f[I]tv\fP [ \f[I]tz\fP ] ]
The \f[I]gettimeofday\fP(2) system call.
.\" ----------  H  ---------------------------------------------------------
.\" ----------  I  ---------------------------------------------------------
.\" ----------  J  ---------------------------------------------------------
.\" ----------  K  ---------------------------------------------------------
.\" ----------  L  ---------------------------------------------------------
.TP 8n
lchown \f[I]pathname\fP \f[I]owner\fP \f[I]group\fP
The \f[I]lchown\fP(2) system call.
.TP 8n
link \f[I]oldpath\fP \f[I]newpath\fP
The \f[I]link\fP(2) system call.
.TP 8n
lseek \f[I]fildes\fP \f[I]offset\fP \f[I]whence\fP
The \f[I]lseek\fP(2) system call.
.TP 8n
lstat \f[I]pathname\fP
The \f[I]lstat\fP(2) system call.
.\" ----------  M  ---------------------------------------------------------
.TP 8n
mkdir \f[I]pathname\fP [ \f[I]mode\fP ]
The \f[I]mkdir\dP(2) system call.
.\" ----------  N  ---------------------------------------------------------
.\" ----------  O  ---------------------------------------------------------
.TP 8n
open \f[I]pathname\fP \f[I]flags\fP [ \f[I]mode\fP ]
The \f[I]open\fP(2) system call.
The \f[I]pathname\fP argument may need to be quoted to insulate white space and
punctuation from the shell.
The \f[I]flags\fP argument may be numeric or symbolic.
The \f[I]mode\fP argument may be numeric or symbolic.
.TP 8n
opendir \f[I]pathname\fP
The \f[I]opendir\fP(3) system call.
.\" ----------  P  ---------------------------------------------------------
.\" ----------  Q  ---------------------------------------------------------
.\" ----------  R  ---------------------------------------------------------
.TP 8n
read \f[I]fildes\fP \f[I]data\fP \f[I]data-size\fP
The \f[I]read\fP(2) system call.
.TP 8n
rename \f[I]oldpath\fP \f[I]newpath\fP
The \f[I]rename\fP(2) system call.
.\" ----------  S  ---------------------------------------------------------
.TP 8n
socket \f[I]domain\fP \f[I]type\fP \f[I]protocol\fP
The \f[I]socket\fP(2) system call.
.TP 8n
stat \f[I]pathname\fP
The \f[I]stat\fP(2) system call.
.TP 8n
strerror
The error given will be printed out with all known detail.
.TP 8n
rename ymlinkf[I]oldpath\fP \f[I]newpath\fP
The \f[I]ymlinkename\fP(2) system call.
.TP 8n
system \f[I]command\fP
The \f[I]system\fP(3) system call.
.\" ----------  T  ---------------------------------------------------------
.\" ----------  U  ---------------------------------------------------------
.TP 8n
unlink \f[I]pathname\fP
The \f[I]unlink\fP(2) system call.
.TP 8n
utime \f[I]pathname\fP [ \f[I]times\fP ]
The \f[I]utime\fP(2) system call.
.\" ----------  V  ---------------------------------------------------------
.\" ----------  W  ---------------------------------------------------------
.TP 8n
wait \f[I]status\fP
The \f[I]wait\fP(2) system call.
.TP 8n
wait3 \f[I]status\fP \f[I]options\fP \f[I]rusage\fP
The \f[I]wait3\fP(2) system call.
.TP 8n
wait4 \f[I]pid\fP \f[I]status\fP \f[I]options\fP \f[I]rusage\fP
The \f[I]wait4\fP(2) system call.
.TP 8n
waitpid \f[I]pid\fP \f[I]status\fP \f[I]options\fP
The \f[I]waitpid\fP(2) system call.
.TP 8n
write \f[I]fildes\fP \f[I]data\fP \f[I]data-size\fP
The \f[I]write\fP(2) system call.
.\" ----------  X  ---------------------------------------------------------
.\" ----------  Y  ---------------------------------------------------------
.\" ----------  Z  ---------------------------------------------------------
.\" ------------------------------------------------------------------------
.PP
Do not include the perentheses used to make the call.
.SH OPTIONS
The \*(n) command understands the following options:
.TP 8n
\f[I]\-e\fP \f[I]number\fP
The value of \f[I]errno\fP as a number (\f[I]e.g.\fP 2),
or as a symbol (\f[I]e.g.\fP ENOENT),
or as the text of its meaning (\f[I]e.g.\fP No such file or directory\fP).
You will need quotes to insulate spaces and punctuation from the shell.
.TP 8n
\f[B]\-V\fP
Print the version of the \f[I]\*(n)\fP executing.
.SH EXIT STATUS
The \*(n) command exits with status 1 on any error.
The \*(n) command only exits with status 0 if there are no errors.
.SH COPYRIGHT
.if n .ds C) (C)
.if t .ds C) \(co
.so etc/version.so
\*(n) version \*(v)
.br
Copyright
\*(C)
\*(Y)
Peter Miller
.SH AUTHOR
Written by Peter Miller <millerp@canb.auug.org.au>
